### ISSUE TITLE
Assets Folder fehlt

### ISSUE THREAD

**Issue by smeerws** [3ahmns2122mtin/HelloAgainCSchrofner#2]

**Comment by smeerws** [comment]
![cschrof](https://user-images.githubusercontent.com/28704310/144445091-b057dd71-65b9-4253-9e25-289879c91faf.JPG)

Das mit dem geteilt raufladen hat so mal funktioniert. Schau bitte in die Hierarchy. wenn das mit deinem Projekt übereinstimmt dann ist das gut und das nächste Projekt auch so herrichten. Bitte hier kurz anworten, ob es passt.

**Comment by CSchrofner** [comment]
Stimmt genau überein, danke!
